# Generated by Django 5.0.6 on 2024-07-07 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_auther_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='usr',
            new_name='user',
        ),
    ]
